services:
  db:
    image: pgvector/pgvector:pg17-trixie
    container_name: notebook_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notebook
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: []
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  ollama:
    build: 
      dockerfile: ollama.dockerfile 
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama
    healthcheck: 
      test: ["ollama", "ps"]
      interval: 30s
      timeout: 1m
      retries: 5
      start_period: 1m

  app:
    build:
      dockerfile: app.dockerfile
    ports:
      - "8000:8000"
    networks:
      - db
      - ollama 
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    
    health_check:
      test: []

volumes:
  postgres_data:
  ollama_data:
