"""initial migration

Revision ID: a1aae69b5042
Revises: 
Create Date: 2026-08-10 14:06:59.111227

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a1aae69b5042'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
