"""added_notebooks_and_messages

Revision ID: b28db42ff7e2
Revises: 667bbda13c38
Create Date: 2026-09-23 18:25:21.816915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28db42ff7e2'
down_revision: Union[str, Sequence[str], None] = '667bbda13c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_owner_id', sa.Integer(), nullable=False),
    sa.Column('notebook_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook_owner_id', 'notebook_name', name='uq_notebook_owner_name')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_assigned_id', sa.Integer(), nullable=False),
    sa.Column('message_owner_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notebook_assigned_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'notebooks', ['notebook_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'notebook_id')
    op.drop_table('messages')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
