"""added hash to document table

Revision ID: eab7d618c9ac
Revises: bc88487053a5
Create Date: 2026-08-15 23:07:53.178047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab7d618c9ac'
down_revision: Union[str, Sequence[str], None] = 'bc88487053a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_hash')
    # ### end Alembic commands ###
