"""pgvector addition

Revision ID: fb630925efaf
Revises: a1aae69b5042
Create Date: 2026-08-13 14:23:05.407451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb630925efaf'
down_revision: Union[str, Sequence[str], None] = 'a1aae69b5042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
