name: Mypy

on: 
  push:
  pull_request:

jobs:
  mypy:
    name: Static type checker with mypy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: uv setup
        uses: astral-sh/setup-uv@v6

      - name: Install python
        run: uv python install 3.14

      - name: Sync packages via uv 
        run: uv sync --locked

      - name: Run mypy
        run:  uv run mypy main.py
